# .zshenv is loaded every time, prior to zprofile or zshrc.

#setopt SOURCE_TRACE # This will print a message every time a file is sourced.

[[ -z $GLOSS_ENV ]] && source /usr/local/gloss/zsh/env.zsh
