# .zshrc is sourced for interactive shells. Loaded after .zprofile.

source /opt/gloss/zsh/rc.zsh
source /opt/gloss/zsh/aliases.zsh

# Run compinit after all fpath customization so it discovers and caches every completion function.
autoload -Uz compinit && compinit
