# .zshrc is sourced for interactive shells. Loaded after .zprofile.

source /opt/gloss/zsh/rc.zsh
source /opt/gloss/zsh/aliases.zsh

# zstyle commands must come before the completion system is initialized.
# Therefore gloss relies on the end user to call autoload for themselves.
autoload -Uz compinit && compinit
