# Dedicated to the public domain under CC0: https://creativecommons.org/publicdomain/zero/1.0/.

# Transcribed from NSEvent.h.

keys = {
  '\uF700' : 'up', # NSUpArrowFunctionKey.
  '\uF701' : 'down', # NSDownArrowFunctionKey.
  '\uF702' : 'left', # NSLeftArrowFunctionKey.
  '\uF703' : 'right', # NSRightArrowFunctionKey.
  '\uF704' : 'f1', # NSF1FunctionKey.
  '\uF705' : 'f2', # NSF2FunctionKey.
  '\uF706' : 'f3', # NSF3FunctionKey.
  '\uF707' : 'f4', # NSF4FunctionKey.
  '\uF708' : 'f5', # NSF5FunctionKey.
  '\uF709' : 'f6', # NSF6FunctionKey.
  '\uF70A' : 'f7', # NSF7FunctionKey.
  '\uF70B' : 'f8', # NSF8FunctionKey.
  '\uF70C' : 'f9', # NSF9FunctionKey.
  '\uF70D' : 'f10', # NSF10FunctionKey.
  '\uF70E' : 'f11', # NSF11FunctionKey.
  '\uF70F' : 'f12', # NSF12FunctionKey.
  '\uF710' : 'f13', # NSF13FunctionKey.
  '\uF711' : 'f14', # NSF14FunctionKey.
  '\uF712' : 'f15', # NSF15FunctionKey.
  '\uF713' : 'f16', # NSF16FunctionKey.
  '\uF714' : 'f17', # NSF17FunctionKey.
  '\uF715' : 'f18', # NSF18FunctionKey.
  '\uF716' : 'f19', # NSF19FunctionKey.
  '\uF717' : 'f20', # NSF20FunctionKey.
  '\uF718' : 'f21', # NSF21FunctionKey.
  '\uF719' : 'f22', # NSF22FunctionKey.
  '\uF71A' : 'f23', # NSF23FunctionKey.
  '\uF71B' : 'f24', # NSF24FunctionKey.
  '\uF71C' : 'f25', # NSF25FunctionKey.
  '\uF71D' : 'f26', # NSF26FunctionKey.
  '\uF71E' : 'f27', # NSF27FunctionKey.
  '\uF71F' : 'f28', # NSF28FunctionKey.
  '\uF720' : 'f29', # NSF29FunctionKey.
  '\uF721' : 'f30', # NSF30FunctionKey.
  '\uF722' : 'f31', # NSF31FunctionKey.
  '\uF723' : 'f32', # NSF32FunctionKey.
  '\uF724' : 'f33', # NSF33FunctionKey.
  '\uF725' : 'f34', # NSF34FunctionKey.
  '\uF726' : 'f35', # NSF35FunctionKey.
  '\uF727' : 'insert', # NSInsertFunctionKey.
  '\uF728' : 'delete', # NSDeleteFunctionKey.
  '\uF729' : 'home', # NSHomeFunctionKey.
  '\uF72A' : 'begin', # NSBeginFunctionKey.
  '\uF72B' : 'end', # NSEndFunctionKey.
  '\uF72C' : 'pageup', # NSPageUpFunctionKey.
  '\uF72D' : 'pagedown', # NSPageDownFunctionKey.
  '\uF72E' : 'printscreen', # NSPrintScreenFunctionKey.
  '\uF72F' : 'scrolllock', # NSScrollLockFunctionKey.
  '\uF730' : 'pause', # NSPauseFunctionKey.
  '\uF731' : 'sysreq', # NSSysReqFunctionKey.
  '\uF732' : 'break', # NSBreakFunctionKey.
  '\uF733' : 'reset', # NSResetFunctionKey.
  '\uF734' : 'stop', # NSStopFunctionKey.
  '\uF735' : 'menu', # NSMenuFunctionKey.
  '\uF736' : 'user', # NSUserFunctionKey.
  '\uF737' : 'system', # NSSystemFunctionKey.
  '\uF738' : 'print', # NSPrintFunctionKey.
  '\uF739' : 'clearline', # NSClearLineFunctionKey.
  '\uF73A' : 'cleardisplay', # NSClearDisplayFunctionKey.
  '\uF73B' : 'insertline', # NSInsertLineFunctionKey.
  '\uF73C' : 'deleteline', # NSDeleteLineFunctionKey.
  '\uF73D' : 'insertchar', # NSInsertCharFunctionKey.
  '\uF73E' : 'deletechar', # NSDeleteCharFunctionKey.
  '\uF73F' : 'prev', # NSPrevFunctionKey.
  '\uF740' : 'next', # NSNextFunctionKey.
  '\uF741' : 'select', # NSSelectFunctionKey.
  '\uF742' : 'execute', # NSExecuteFunctionKey.
  '\uF743' : 'undo', # NSUndoFunctionKey.
  '\uF744' : 'redo', # NSRedoFunctionKey.
  '\uF745' : 'find', # NSFindFunctionKey.
  '\uF746' : 'help', # NSHelpFunctionKey.
  '\uF747' : 'modeswitch', # NSModeSwitchFunctionKey.
}
